model:
  d_model: 64
  nhead: 8
  num_encoder_layers: 1
  num_decoder_layers: 1
  dim_feedforward: 512
  max_len: 500
training:
  epochs: 170
  lr: 0.0001
  weight_decay: 0.00001
  max_grad_norm: 0.5
data:
  min_trajectory_length: 10
  rollout_steps: 5
yolo:
  ball_class: 0
  conf_threshold: 0.1